import { Trade, DailyJournal, TradingRule, UserRiskSettings, RuleViolation } from '@/types';

export function getSampleTrades(): Trade[] {
  return [
    {
      id: 'trade-101',
      user_id: 'demo-user',
      trade_date: '2026-08-03',
      entry_time: '09:20',
      exit_time: '09:45',
      instrument: 'NIFTY',
      symbol: 'NIFTY 24500 CE',
      expiry: '2026-08-06',
      option_type: 'CE',
      strike_price: 24500,
      position_type: 'Long',
      quantity: 75,
      lots: 1,
      entry_price: 120,
      exit_price: 155,
      stop_loss: 105,
      target: 150,
      planned_risk: 1125,
      planned_reward: 2250,
      brokerage: 40,
      taxes_charges: 15,
      gross_pnl: 2625,
      net_pnl: 2570,
      risk_reward_ratio: 2.33,
      percentage_return: 29.1,
      points_gained: 35,
      trade_duration_mins: 25,
      trade_quality_score: 92,
      market_trend: 'Bullish',
      htf_trend: 'Bullish',
      entry_timeframe: '5m',
      market_condition: 'Breakout',
      strategy: 'Breakout',
      technical_confirmations: ['VWAP bounce', 'Volume spike', '9 EMA crossover'],
      entry_reason: '5m candle closed above previous day high with high volume.',
      stop_loss_reason: 'Below 5m swing low.',
      target_reason: '1.5x ADR target level.',
      expected_scenario: 'Uptrend continuation.',
      invalidating_condition: 'Close back inside previous day range.',
      notes: 'Clean execution according to plan.',
      mistakes: [],
      psychology: {
        emotion_before: 'Calm',
        emotion_during: 'Confident',
        emotion_after: 'Confident',
        discipline_score: 9,
        confidence_before: 8,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
        emotional_notes: 'Felt calm and patient before entry.',
      },
    },
    {
      id: 'trade-102',
      user_id: 'demo-user',
      trade_date: '2026-08-04',
      entry_time: '10:15',
      exit_time: '10:30',
      instrument: 'BANKNIFTY',
      symbol: 'BANKNIFTY 52200 PE',
      expiry: '2026-08-06',
      option_type: 'PE',
      strike_price: 52200,
      position_type: 'Long',
      quantity: 30,
      lots: 2,
      entry_price: 240,
      exit_price: 195,
      stop_loss: 200,
      target: 320,
      planned_risk: 1200,
      planned_reward: 2400,
      brokerage: 40,
      taxes_charges: 15,
      gross_pnl: -1350,
      net_pnl: -1405,
      risk_reward_ratio: 2.0,
      percentage_return: -18.75,
      points_gained: -45,
      trade_duration_mins: 15,
      trade_quality_score: 85,
      market_trend: 'Bearish',
      htf_trend: 'Bearish',
      entry_timeframe: '5m',
      market_condition: 'Trending',
      strategy: 'Pullback',
      technical_confirmations: ['20 EMA rejection', 'Lower high structure'],
      entry_reason: '5m pullback rejection at 20 EMA.',
      stop_loss_reason: 'Above pullback high.',
      target_reason: 'Previous day low.',
      expected_scenario: 'Downtrend resumption.',
      notes: 'Controlled loss. Market reversed abruptly on HDFC Bank news.',
      mistakes: [],
      psychology: {
        emotion_before: 'Confident',
        emotion_during: 'Calm',
        emotion_after: 'Neutral',
        discipline_score: 9,
        confidence_before: 8,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
        emotional_notes: 'Respected original stop loss without hesitation.',
      },
    },
    {
      id: 'trade-103',
      user_id: 'demo-user',
      trade_date: '2026-08-04',
      entry_time: '10:35',
      exit_time: '11:10',
      instrument: 'BANKNIFTY',
      symbol: 'BANKNIFTY 52400 CE',
      expiry: '2026-08-06',
      option_type: 'CE',
      strike_price: 52400,
      position_type: 'Long',
      quantity: 45,
      lots: 3,
      entry_price: 210,
      exit_price: 130,
      stop_loss: 180,
      target: 270,
      planned_risk: 1350,
      planned_reward: 2700,
      brokerage: 40,
      taxes_charges: 20,
      gross_pnl: -3600,
      net_pnl: -3660,
      risk_reward_ratio: 2.0,
      percentage_return: -38.1,
      points_gained: -80,
      trade_duration_mins: 35,
      trade_quality_score: 30,
      market_trend: 'Sideways',
      htf_trend: 'Bearish',
      entry_timeframe: '1m',
      market_condition: 'High volatility',
      strategy: 'Breakout',
      technical_confirmations: [],
      entry_reason: 'Immediate entry right after loss on Trade #102.',
      stop_loss_reason: 'Moved SL down from 180 to 130.',
      target_reason: 'Hoped for fast recovery.',
      notes: 'Classic revenge trade & moved stop loss!',
      mistakes: ['Revenge trading', 'Moved stop-loss', 'FOMO entry'],
      psychology: {
        emotion_before: 'Revenge',
        emotion_during: 'Fearful',
        emotion_after: 'Angry',
        discipline_score: 2,
        confidence_before: 4,
        followed_plan: 'No',
        moved_stop_loss: true,
        exited_early: false,
        held_loss_hoping: true,
        revenge_trade: true,
        overtraded: true,
        fomo_entry: true,
        increased_risk_after_loss: true,
        emotional_notes: 'Felt angry after loss #1 and jumped straight back in.',
      },
    },
    {
      id: 'trade-104',
      user_id: 'demo-user',
      trade_date: '2026-08-07',
      entry_time: '14:10',
      exit_time: '14:50',
      instrument: 'NIFTY',
      symbol: 'NIFTY 24600 CE',
      expiry: '2026-08-13',
      option_type: 'CE',
      strike_price: 24600,
      position_type: 'Long',
      quantity: 150,
      lots: 2,
      entry_price: 95,
      exit_price: 132,
      stop_loss: 80,
      target: 125,
      planned_risk: 2250,
      planned_reward: 4500,
      brokerage: 40,
      taxes_charges: 20,
      gross_pnl: 5550,
      net_pnl: 5490,
      risk_reward_ratio: 2.47,
      percentage_return: 38.9,
      points_gained: 37,
      trade_duration_mins: 40,
      trade_quality_score: 88,
      market_trend: 'Bullish',
      htf_trend: 'Bullish',
      entry_timeframe: '15m',
      market_condition: 'Trending',
      strategy: 'Pullback',
      technical_confirmations: ['VWAP bounce', 'Supertrend green'],
      entry_reason: '15m higher low formation near VWAP.',
      stop_loss_reason: 'Below 15m swing low.',
      notes: 'Disciplined trade.',
      mistakes: [],
      psychology: {
        emotion_before: 'Calm',
        emotion_during: 'Calm',
        emotion_after: 'Confident',
        discipline_score: 9,
        confidence_before: 8,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
      },
    },
    {
      id: 'trade-105',
      user_id: 'demo-user',
      trade_date: '2026-08-11',
      entry_time: '09:25',
      exit_time: '10:05',
      instrument: 'FINNIFTY',
      symbol: 'FINNIFTY 23100 PE',
      expiry: '2026-08-11',
      option_type: 'PE',
      strike_price: 23100,
      position_type: 'Long',
      quantity: 80,
      lots: 2,
      entry_price: 65,
      exit_price: 110,
      stop_loss: 50,
      target: 95,
      planned_risk: 1200,
      planned_reward: 2400,
      brokerage: 40,
      taxes_charges: 15,
      gross_pnl: 3600,
      net_pnl: 3545,
      risk_reward_ratio: 3.0,
      percentage_return: 69.2,
      points_gained: 45,
      trade_duration_mins: 40,
      trade_quality_score: 95,
      market_trend: 'Bearish',
      htf_trend: 'Bearish',
      entry_timeframe: '5m',
      market_condition: 'Breakout',
      strategy: 'Breakout',
      technical_confirmations: ['Opening Range Breakdown', 'Heavy volume'],
      entry_reason: '5m ORB breakdown on Finnifty Expiry day.',
      notes: 'Perfect expiry trade.',
      mistakes: [],
      psychology: {
        emotion_before: 'Calm',
        emotion_during: 'Confident',
        emotion_after: 'Excited',
        discipline_score: 10,
        confidence_before: 9,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
      },
    },
    {
      id: 'trade-106',
      user_id: 'demo-user',
      trade_date: '2026-08-14',
      entry_time: '11:45',
      exit_time: '12:15',
      instrument: 'NIFTY',
      symbol: 'NIFTY 24700 PE',
      expiry: '2026-08-20',
      option_type: 'PE',
      strike_price: 24700,
      position_type: 'Long',
      quantity: 75,
      lots: 1,
      entry_price: 110,
      exit_price: 82,
      stop_loss: 90,
      target: 150,
      planned_risk: 1500,
      planned_reward: 3000,
      brokerage: 40,
      taxes_charges: 15,
      gross_pnl: -2100,
      net_pnl: -2155,
      risk_reward_ratio: 2.0,
      percentage_return: -25.4,
      points_gained: -28,
      trade_duration_mins: 30,
      trade_quality_score: 45,
      market_trend: 'Sideways',
      htf_trend: 'Bullish',
      entry_timeframe: '3m',
      market_condition: 'Range',
      strategy: 'Reversal',
      technical_confirmations: [],
      entry_reason: 'Tried to catch top in range market.',
      notes: 'Counter trend trade without confirmation.',
      mistakes: ['Entered without confirmation', 'Took a trade outside my setup'],
      psychology: {
        emotion_before: 'FOMO',
        emotion_during: 'Nervous',
        emotion_after: 'Neutral',
        discipline_score: 5,
        confidence_before: 5,
        followed_plan: 'No',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: true,
        increased_risk_after_loss: false,
      },
    },
    {
      id: 'trade-107',
      user_id: 'demo-user',
      trade_date: '2026-08-20',
      entry_time: '09:40',
      exit_time: '10:20',
      instrument: 'BANKNIFTY',
      symbol: 'BANKNIFTY 52800 CE',
      expiry: '2026-08-20',
      option_type: 'CE',
      strike_price: 52800,
      position_type: 'Long',
      quantity: 30,
      lots: 2,
      entry_price: 180,
      exit_price: 265,
      stop_loss: 150,
      target: 240,
      planned_risk: 900,
      planned_reward: 1800,
      brokerage: 40,
      taxes_charges: 15,
      gross_pnl: 2550,
      net_pnl: 2495,
      risk_reward_ratio: 2.83,
      percentage_return: 47.2,
      points_gained: 85,
      trade_duration_mins: 40,
      trade_quality_score: 90,
      market_trend: 'Bullish',
      htf_trend: 'Bullish',
      entry_timeframe: '5m',
      market_condition: 'Trending',
      strategy: 'Breakout',
      technical_confirmations: ['VWAP support', 'RSI 60+'],
      entry_reason: '5m breakout on Banknifty Expiry day.',
      notes: 'Rode the trend well.',
      mistakes: [],
      psychology: {
        emotion_before: 'Calm',
        emotion_during: 'Confident',
        emotion_after: 'Confident',
        discipline_score: 9,
        confidence_before: 8,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
      },
    },
    {
      id: 'trade-108',
      user_id: 'demo-user',
      trade_date: '2026-08-25',
      entry_time: '13:15',
      exit_time: '13:35',
      instrument: 'NIFTY',
      symbol: 'NIFTY 24800 CE',
      expiry: '2026-08-27',
      option_type: 'CE',
      strike_price: 24800,
      position_type: 'Long',
      quantity: 75,
      lots: 1,
      entry_price: 88,
      exit_price: 120,
      stop_loss: 70,
      target: 115,
      planned_risk: 1350,
      planned_reward: 2025,
      brokerage: 40,
      taxes_charges: 15,
      gross_pnl: 2400,
      net_pnl: 2345,
      risk_reward_ratio: 1.78,
      percentage_return: 36.3,
      points_gained: 32,
      trade_duration_mins: 20,
      trade_quality_score: 84,
      market_trend: 'Bullish',
      htf_trend: 'Bullish',
      entry_timeframe: '5m',
      market_condition: 'Trending',
      strategy: 'Pullback',
      technical_confirmations: ['9 EMA bounce'],
      entry_reason: '5m pullback to 9 EMA.',
      notes: 'Good risk reward.',
      mistakes: [],
      psychology: {
        emotion_before: 'Calm',
        emotion_during: 'Calm',
        emotion_after: 'Confident',
        discipline_score: 8,
        confidence_before: 7,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
      },
    },
    {
      id: 'trade-109',
      user_id: 'demo-user',
      trade_date: '2026-08-31',
      entry_time: '09:25',
      exit_time: '09:55',
      instrument: 'NIFTY',
      symbol: 'NIFTY 24500 CE',
      expiry: '2026-09-03',
      option_type: 'CE',
      strike_price: 24500,
      position_type: 'Long',
      quantity: 150,
      lots: 2,
      entry_price: 140,
      exit_price: 185,
      stop_loss: 120,
      target: 175,
      planned_risk: 3000,
      planned_reward: 5250,
      brokerage: 40,
      taxes_charges: 20,
      gross_pnl: 6750,
      net_pnl: 6690,
      risk_reward_ratio: 2.25,
      percentage_return: 32.1,
      points_gained: 45,
      trade_duration_mins: 30,
      trade_quality_score: 94,
      market_trend: 'Bullish',
      htf_trend: 'Bullish',
      entry_timeframe: '5m',
      market_condition: 'Trending',
      strategy: 'Breakout',
      technical_confirmations: ['VWAP bounce', 'Support/resistance'],
      entry_reason: '5m pullback to VWAP + 9 EMA in strong morning uptrend.',
      stop_loss_reason: 'Below VWAP band.',
      target_reason: 'Morning high retest.',
      notes: 'Stuck to plan 100%. Held till full target.',
      mistakes: [],
      psychology: {
        emotion_before: 'Calm',
        emotion_during: 'Confident',
        emotion_after: 'Confident',
        discipline_score: 9,
        confidence_before: 8,
        followed_plan: 'Yes',
        moved_stop_loss: false,
        exited_early: false,
        held_loss_hoping: false,
        revenge_trade: false,
        overtraded: false,
        fomo_entry: false,
        increased_risk_after_loss: false,
      },
    },
  ];
}

export function getSampleDailyJournals(): DailyJournal[] {
  return [
    {
      id: 'journal-2026-08-03',
      user_id: 'demo-user',
      journal_date: '2026-08-03',
      completed: true,
      daily_pnl: 2570,
      trade_count: 1,
      discipline_score: 9,
      followed_plan: 'Yes',
      yesterday_rule: 'Wait for 5m candle close before entering breakouts.',
      followed_yesterday_rule: 'Yes',
      yesterday_rule_notes: 'Patiently waited for 9:20 candle close on NIFTY.',
      selected_mistakes: [],
      what_happened_today: 'NIFTY opened with a gap up. I waited patiently for the 9:20 5m candle close above previous day high before buying the 24500 CE. Held until 2.3R target.',
      biggest_mistake: 'None today.',
      why_made_mistake: 'Maintained great focus and respected my entry rules.',
      root_cause: "Didn't follow my rules",
      root_cause_explanation: 'N/A - Followed plan strictly.',
      pre_market_emotion: 'Calm',
      during_market_emotion: 'Confident',
      post_market_emotion: 'Confident',
      emotional_control_score: 9,
      what_did_well: 'Waited for candle close instead of jumping in on the 1m chart.',
      what_went_wrong: 'Nothing.',
      what_learned: 'Patience at market open pays off consistently.',
      do_differently_tomorrow: 'Keep position size fixed at 1 lot for NIFTY.',
      tomorrow_rule: 'Never enter a trade in the first 5 minutes of market open.',
    },
    {
      id: 'journal-2026-08-04',
      user_id: 'demo-user',
      journal_date: '2026-08-04',
      completed: true,
      daily_pnl: -5065,
      trade_count: 2,
      discipline_score: 3,
      followed_plan: 'No',
      yesterday_rule: 'Never enter a trade in the first 5 minutes of market open.',
      followed_yesterday_rule: 'Yes',
      yesterday_rule_notes: 'Waited till 10:15 AM before entering.',
      selected_mistakes: ['Revenge trading', 'Moved stop-loss', 'FOMO entry'],
      what_happened_today: 'Trade #1 was a disciplined loss (-₹1,405). However, I got frustrated by the abrupt loss and immediately jumped into BankNifty 52400 CE without a setup. I widened my SL from 180 to 130 hoping it would turn around.',
      biggest_mistake: 'Revenge trading',
      why_made_mistake: 'Could not accept the first loss and wanted to recover money immediately.',
      root_cause: 'Revenge',
      root_cause_explanation: 'Ego got hurt after the first loss. Wanted to be right instead of following risk management.',
      pre_market_emotion: 'Calm',
      during_market_emotion: 'Angry',
      post_market_emotion: 'Angry',
      emotional_control_score: 3,
      what_did_well: 'Trade #1 was executed according to plan.',
      what_went_wrong: 'Revenge trade on Trade #2 blew up my daily loss limit.',
      what_learned: 'One loss is fine. Over-trading after a loss destroys the whole week.',
      do_differently_tomorrow: 'If I take 1 loss, I must walk away from the screen for 30 minutes.',
      tomorrow_rule: 'Walk away from the screen for 30 minutes after any losing trade.',
    },
    {
      id: 'journal-2026-08-07',
      user_id: 'demo-user',
      journal_date: '2026-08-07',
      completed: true,
      daily_pnl: 5490,
      trade_count: 1,
      discipline_score: 9,
      followed_plan: 'Yes',
      yesterday_rule: 'Walk away from the screen for 30 minutes after any losing trade.',
      followed_yesterday_rule: 'Yes',
      yesterday_rule_notes: 'Remained calm all session. Only took 1 clean setup at 2:10 PM.',
      selected_mistakes: [],
      what_happened_today: 'Waited until 2:10 PM for NIFTY to form a higher low near VWAP on the 15m chart. Took 2 lots of 24600 CE and locked in +₹5,490.',
      biggest_mistake: 'None.',
      why_made_mistake: 'Strict adherence to my rule feedback loop.',
      root_cause: 'Lack of preparation',
      root_cause_explanation: 'N/A - Excellent execution.',
      pre_market_emotion: 'Calm',
      during_market_emotion: 'Calm',
      post_market_emotion: 'Confident',
      emotional_control_score: 9,
      what_did_well: 'Ignored noisy mid-day chop and waited for 2 PM trend move.',
      what_went_wrong: 'None.',
      what_learned: 'Higher timeframe (15m) setups have much higher win rate.',
      do_differently_tomorrow: 'Continue prioritizing 15m structural confirmations.',
      tomorrow_rule: 'No trades between 12:00 PM and 1:30 PM.',
    },
    {
      id: 'journal-2026-08-31',
      user_id: 'demo-user',
      journal_date: '2026-08-31',
      completed: true,
      daily_pnl: 6690,
      trade_count: 1,
      discipline_score: 9,
      followed_plan: 'Yes',
      yesterday_rule: 'No trades between 12:00 PM and 1:30 PM.',
      followed_yesterday_rule: 'Yes',
      yesterday_rule_notes: 'Traded at 9:25 AM and finished for the day by 10 AM.',
      selected_mistakes: [],
      what_happened_today: 'Entered NIFTY 24500 CE on a 5m pullback to VWAP + 9 EMA in a strong morning uptrend. Trailed SL along 9 EMA and exited near morning high for +₹6,690.',
      biggest_mistake: 'None.',
      why_made_mistake: 'Followed pre-market plan 100%.',
      root_cause: 'Lack of confidence',
      root_cause_explanation: 'N/A - High discipline score.',
      pre_market_emotion: 'Calm',
      during_market_emotion: 'Confident',
      post_market_emotion: 'Confident',
      emotional_control_score: 9,
      what_did_well: 'Stuck to 1 single trade and shut down terminal immediately after booking profits.',
      what_went_wrong: 'None.',
      what_learned: '1 trade a day with high conviction is all that is needed.',
      do_differently_tomorrow: 'Keep maximum trades per day capped at 2.',
      tomorrow_rule: 'Stop trading for the day as soon as net P&L exceeds +₹3,000.',
    },
  ];
}

export function getSampleTradingRules(): TradingRule[] {
  return [
    {
      id: 'rule-1',
      user_id: 'demo-user',
      rule_name: 'Always use Stop Loss',
      description: 'Never enter a trade without an active hard stop-loss.',
      enabled: true,
    },
    {
      id: 'rule-2',
      user_id: 'demo-user',
      rule_name: 'No Revenge Trading',
      description: 'Do not take immediate trades after a loss to recover money.',
      enabled: true,
    },
    {
      id: 'rule-3',
      user_id: 'demo-user',
      rule_name: 'Max 3 Trades Per Day',
      description: 'Cap daily trading activity to a maximum of 3 trades.',
      enabled: true,
    },
    {
      id: 'rule-4',
      user_id: 'demo-user',
      rule_name: 'No Over-leveraging',
      description: 'Max risk per trade must not exceed ₹2,000.',
      enabled: true,
    },
  ];
}

export function getSampleRiskSettings(): UserRiskSettings {
  return {
    id: 'risk-settings-1',
    user_id: 'demo-user',
    capital: 150000,
    max_risk_per_trade: 2000,
    max_daily_loss: 5000,
    max_trades_per_day: 3,
    max_consecutive_losses: 2,
    max_position_size: 300,
  };
}

export function getSampleRuleViolations(): RuleViolation[] {
  return [
    {
      id: 'viol-1',
      user_id: 'demo-user',
      trade_id: 'trade-103',
      violation_name: 'Revenge Trading & Stop Loss Widened',
      pnl_impact: -3660,
      notes: 'Entered without technical confirmation and widened stop loss.',
    },
  ];
}
